spring:
  application:
    name: food-dairy
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5434/postgres}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER:test_admin}
    password: ${DATA_PASSWORD:1111}
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
bot:
  name: ${BOT_NAME:kamae_test_bot}
  token: ${BOT_TOKEN:7262535656:AAGR1DnFLtQ6lm87sUbyRRjntkuCeaRcnTw}